int _putchar(char c);
int _islower(void);
int _isalpha(void);
int _abs(void);
int _isupper(void);
int _isdigit(void);
int _strlen(void);
void _puts(char *s);
char *_strcpy(void);
int _atoi(void);
char *_strcat(void);
char *_strncat(void);
char *_strncpy(void);
int _strcmp(void);
char *_memset(void);
char *_memcpy(void);
char *_strchr(void);
unsigned int _strspn(void);
char *_strpbrk(void);
char *_strstr(void);
